# Quarto

Note: This chapter was about R Markdown when previous cohorts read it.
When you update these slides to reflect the updated chapter, please remove this note.

**Learning objectives:**

- **Create R Markdown documents.**
- **Format text** using Pandoc’s Markdown.
- Include **R code chunks** in an R Markdown document.
- Use **chunk options** to change what displays in an R Markdown document.
- Use **`knitr::kable`** to display formatted tables in an R Markdown document.
- **Cache data** in an R Markdown document.
- Set **global chunk options** in an R Markdown document.
- Embed **inline code** in an R Markdown document.


## Slide 1

Slide contents. 
Keep it short and slide-like!

## Slide 2

Slide contents.

## Meeting Videos

### Cohort 5

`r knitr::include_url("https://www.youtube.com/embed/wAzYA01hojo")`

<details>
  <summary> Meeting chat log </summary>
  
```
00:03:37	Njoki Njuki Lucy:	I agree with Ryan.
00:15:27	Ryan Metcalf:	https://pandoc.org/
00:20:48	Ryan Metcalf:	Some extra reading material: https://www.w3.org/TR/WD-html40-970708/intro/sgmltut.html
00:28:14	Njoki Njuki Lucy:	Qn, does anyone know why putting figure captions move figures to other positions?
00:33:58	Federica Gazzelloni:	try with {r ….., fig.align =“center”}
00:35:01	Njoki Njuki Lucy:	Thanks Federica, I'll give it a try :)
00:57:25	Ryan Metcalf:	https://daringfireball.net/projects/markdown/
00:58:59	Ryan Metcalf:	The comment I’m making, there are many forms of Markdown, not all created equally. John Gruber originated Markdown syntax to make authoring easier. GitHub versus GitLab, versus RMarkdonw, etc...
01:02:40	Federica Gazzelloni:	you can set your path: opts_chunk$set(cache.path = " ")
01:04:42	Federica Gazzelloni:	https://bookdown.org/yihui/rmarkdown-cookbook/cache.html
01:06:13	Ryan Metcalf:	https://quarto.org/
01:07:57	Federica Gazzelloni:	The most appropriate use case of caching is to save and reload R objects that take too long to compute in a code chunk
01:09:20	Njoki Njuki Lucy:	no
01:09:26	Federica Gazzelloni:	no
01:12:49	Njoki Njuki Lucy:	I'll have to leave, thanks Becki! I look forward to the other part!!
01:12:53	Federica Gazzelloni:	there is some more about the changing r session and the cache: https://www.r-bloggers.com/2021/07/caching-the-results-of-functions-of-your-r-package/
01:13:02	Becki R. (she/her):	Bye Lucy!
```
</details>

`r knitr::include_url("https://www.youtube.com/embed/2MGp74nb2ig")`

<details>
  <summary> Meeting chat log </summary>
  
```
00:10:00	Jon Harmon (jonthegeek):	bestbook.cool
00:11:26	Jon Harmon (jonthegeek):	https://podcast.bestbook.cool/
00:28:01	Jon Harmon (jonthegeek):	happygitwithr.com
00:30:59	Jon Harmon (jonthegeek):	Remind @Sandra Muroy to share the dlab GitHub stuff when this posts to our channel. There, I think that will tag you in the post!
00:32:44	Jon Harmon (jonthegeek):	xaringan
00:36:45	Jon Harmon (jonthegeek):	lol, it's just called {shinydashboard}
00:48:24	Becki R. (she/her):	I definitely need help with that!
00:53:08	Jon Harmon (jonthegeek):	It's been a while since we learned that!
2021-08-21: Chapter 6: Workflow: scripts: Ryan Metcalf
01:01:01	Jon Harmon (jonthegeek):	{pak} = updated package tracker
01:01:48	Jon Harmon (jonthegeek):	{targets}
01:03:00	Federica Gazzelloni:	library(pkgsnap)
01:04:15	Jon Harmon (jonthegeek):	devtools::install_version()
01:05:00	Jon Harmon (jonthegeek):	?remotes::install_version()
01:05:15	Jon Harmon (jonthegeek):	install_version("devtools", ">= 1.12.0, < 1.14")
01:07:07	Jon Harmon (jonthegeek):	https://github.com/MangoTheCat/pkgsnap
01:11:32	Jon Harmon (jonthegeek):	https://docs.ropensci.org/targets/
01:11:46	Jon Harmon (jonthegeek):	pkgdown
01:12:41	Jon Harmon (jonthegeek):	https://rsample.tidymodels.org/
01:13:21	Jon Harmon (jonthegeek):	https://pkgdown.r-lib.org/
01:13:32	Sandra Muroy:	https://github.com/dlab-berkeley/Bash-Git
```
</details>


### Cohort 6

`r knitr::include_url("https://www.youtube.com/embed/dG5PcCDMDdI")`

<details>
  <summary> Meeting chat log </summary>
  
```
00:18:56	Marielena Soilemezidi:	https://rstudio.com/resources/cheatsheets/
00:19:07	Daniel:	Thanks
00:59:42	Marielena Soilemezidi:	http://rmarkdown.rstudio.com/developer_parameterized_reports.html#parameter_user_interfaces
```
</details>
