# Quarto formats

Note: This chapter was about R Markdown when previous cohorts read it.
When you update these slides to reflect the updated chapter, please remove this note.

**Learning objectives:**

- **Control R Markdown output** with **output formats** and **options.**
- Recognize the available R Markdown **document formats.**
- **Collaborate** using R Markdown **notebooks.**
- Recognize the available R Markdown **presentation formats.**
- Build dashboards with **`{flexdashboard}`.**
- Add **interactivity** to R Markdown documents.
- Generate **complete websites** with R Markdown.
- Recognize **other R Markdown formats.**

## Slide 1

Slide contents. 
Keep it short and slide-like!

## Slide 2

Slide contents.

## Meeting Videos

### Cohort 5

`r knitr::include_url("https://www.youtube.com/embed/2MGp74nb2ig")`

<details>
  <summary> Meeting chat log </summary>
  
```
00:10:00	Jon Harmon (jonthegeek):	bestbook.cool
00:11:26	Jon Harmon (jonthegeek):	https://podcast.bestbook.cool/
00:28:01	Jon Harmon (jonthegeek):	happygitwithr.com
00:30:59	Jon Harmon (jonthegeek):	Remind @Sandra Muroy to share the dlab GitHub stuff when this posts to our channel. There, I think that will tag you in the post!
00:32:44	Jon Harmon (jonthegeek):	xaringan
00:36:45	Jon Harmon (jonthegeek):	lol, it's just called {shinydashboard}
00:48:24	Becki R. (she/her):	I definitely need help with that!
00:53:08	Jon Harmon (jonthegeek):	It's been a while since we learned that!
2021-08-21: Chapter 6: Workflow: scripts: Ryan Metcalf
01:01:01	Jon Harmon (jonthegeek):	{pak} = updated package tracker
01:01:48	Jon Harmon (jonthegeek):	{targets}
01:03:00	Federica Gazzelloni:	library(pkgsnap)
01:04:15	Jon Harmon (jonthegeek):	devtools::install_version()
01:05:00	Jon Harmon (jonthegeek):	?remotes::install_version()
01:05:15	Jon Harmon (jonthegeek):	install_version("devtools", ">= 1.12.0, < 1.14")
01:07:07	Jon Harmon (jonthegeek):	https://github.com/MangoTheCat/pkgsnap
01:11:32	Jon Harmon (jonthegeek):	https://docs.ropensci.org/targets/
01:11:46	Jon Harmon (jonthegeek):	pkgdown
01:12:41	Jon Harmon (jonthegeek):	https://rsample.tidymodels.org/
01:13:21	Jon Harmon (jonthegeek):	https://pkgdown.r-lib.org/
01:13:32	Sandra Muroy:	https://github.com/dlab-berkeley/Bash-Git
```
</details>

### Cohort 6

`r knitr::include_url("https://www.youtube.com/embed/qQrnNef9fkM")`

<details>
  <summary> Meeting chat log </summary>
  
```
00:09:51	Marielena Soilemezidi:	http://www.thefunctionalart.com/p/instructors-guide.html
https://www.dropbox.com/s/gyqyz3hei7lhhmt/R_RESOURCES.txt?dl=0
https://exts.ggplot2.tidyverse.org/gallery/
00:26:20	Daniel:	underscore
00:26:32	Daniel:	It is called an “underscore”
00:42:17	Daniel:	I can’t see the screen anymore
00:43:00	Daniel:	All good now
00:44:57	Marielena Soilemezidi:	https://github.com/jrnold/ggthemes)
00:55:42	Daniel:	https://stackoverflow.com/questions/23957278/how-to-add-table-of-contents-in-rmarkdown
01:03:59	Daniel:	It’s fine, sorry my internet went off
01:04:17	Marielena Soilemezidi:	http://shiny.rstudio.com/.
01:05:04	Marielena Soilemezidi:	http://rmarkdown.rstudio.com/rmarkdown_websites.html.
01:07:21	Marielena Soilemezidi:	http://colinpurrington.com/tips/lab-notebooks
01:10:02	Marielena Soilemezidi:	https://quarto.org/
```
</details>


### Cohort 7

`r knitr::include_url("https://www.youtube.com/embed/vkjYlBK9-9c")`

<details>
<summary> Meeting chat log </summary>

```
00:08:34	Oluwafemi Oyedele:	We will start in 5 minute time!!!
00:14:37	Oluwafemi Oyedele:	start
00:52:30	Oluwafemi Oyedele:	https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/revealjs/themes
01:09:33	Oluwafemi Oyedele:	https://quarto.org/docs/journals/templates.html
01:10:52	Oluwafemi Oyedele:	stop
```
</details>


### Cohort 8

`r knitr::include_url("https://www.youtube.com/embed/7kW7DEWPVZ8")`

<details>
<summary> Meeting chat log </summary>

```
00:01:59	Shamsuddeen Muhammad:	start
00:10:33	Ahmed Mamdouh:	Im here
00:10:47	Ahmed Mamdouh:	The internet is so bad sorry
00:12:18	Ahmed Mamdouh:	Oh interesting
00:18:39	Ahmed Mamdouh:	It like packaging all dependencies
00:25:58	Ahmed Mamdouh:	Renv is like venv in python
00:29:57	Ahmed Mamdouh:	Yup
00:31:32	Ahmed Mamdouh:	Awesome
00:32:25	Shamsuddeen Muhammad:	stop
00:32:27	Ahmed Mamdouh:	Thanks alot man
00:32:50	Ahmed Mamdouh:	Bye
```
</details>
