--- 
title: "R for Data Science Book Club"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-r4ds
description: "This is the product of the R4DS Online Learning Community's Book Club."
---

# Welcome {-}

This is a companion for the book [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.
This companion is available at [r4ds.io/r4ds](https://r4ds.io/r4ds).

This website is being developed by the [R4DS Online Learning Community](https://rfordatasci.com). Follow along, and [join the community](https://r4ds.io/join) to participate.

This companion follows the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Book club meetings {-}

-   Volunteer leads discussion of a chapter
    -   **This is the best way to learn the material.**
-   Presentations: 
    -   Review of material
    -   Questions you have
    -   Maybe live demo
-   More info about editing: [this github repo](https://github.com/r4ds/bookclub-r4ds).
-   Recorded, available on the [R4DS Online Learning Community YouTube Channel](https://r4ds.io/youtube).

## Pace {-}

-   **Goal:** 1 chapter/week
-   Ok to split overwhelming chapters
-   Ok to combine short chapters
-   Meet ***every*** week except holidays, etc
    -   We'll discuss even if presenter unavailable

## Learning objectives {-}

-   Students who study with LOs in mind ***retain more.***
-   **Tips:**
    -   "After today's session, you will be able to..."
    -   *Very* roughly **1 per section.**
-   Likely need to be refined

## Today's learning objectives {-}

After today's session, you will be able to...

-   Explain how our weekly meetings work.
-   Sign up to lead a discussion.
-   Edit notes on GitHub.
-   (More LOs coming in Chapter 1)

## GitHub {-}

-   Even tech bros can figure it out, ***you'll be fine!***
-   See README for setup instructions
    -   [Cohort 9 Week 1](https://youtu.be/9ar16FGFgT0) included a walk-through
-   Ok to edit directly in browser!
